### ISSUE TITLE
avoid google search indexing old documentation

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane.github.io#107]
are we able to exclude old version content from being indexed at Google?

Searching for "crossplane aws rds" should not result in crossplane v0.3 being the first link.

**Comment by echarles** [comment]
If it is not possible on google level, a mitigation would be to add in the older version a big banner on top of the page saying "Old Version - Please use the latest version".

Now my first reflex when looking at the doc is to select the latest version via the top right selector. Having that banner would ensure at least everyone knows he is not on the latest version.

**Comment by chlunde** [comment]
More info on https://developers.google.com/search/docs/advanced/guidelines/get-started#control-how-google-crawls-and-indexes-your-site

**Comment by echarles** [comment]
oh and there is also the well known `robots.txt` you can put at the root of the site

see also https://developers.google.com/search/docs/advanced/robots/intro

**Comment by echarles** [comment]
> If it is not possible on google level, a mitigation would be to add in the older version a big banner on top of the page saying "Old Version - Please use the latest version".

Looks like the banner is already there. Maybe not visible enough (display it in red color e.g.)

<img width="935" alt="Screenshot 2021-05-07 at 10 34 51" src="https://user-images.githubusercontent.com/226720/117422594-10c39700-af20-11eb-95dd-24370acdebc1.png">

**Comment by negz** [comment]
https://developers.google.com/search/docs/advanced/crawling/block-indexing

Perhaps we could automatically add a `noindex` meta tag to all but the current version of the docs?

**Comment by nabadger** [comment]
This is probably one of my biggest issues - I tend to reference crossplane docs several times a day...out of habit I go via Google, and always end up on the old docs :) 

For anyone new to crossplane will be a bigger problem as people tend to glance over the banner warning them of the old version...(I think anyway).

**Comment by hasheddan** [comment]
@chlunde are you interested in taking a stab at this? Would absolutely be a massive help if it works!

**Comment by chancegraff** [comment]
Thanks @chlunde, your first solution looks like it should do the job according to Google

https://developers.google.com/search/docs/advanced/crawling/block-indexing

> ```
> {% if currentVersion != latestVersion%}
> <meta name="robots" content="noindex">
> {% endif %}
> ```

**Comment by chlunde** [comment]
@hasheddan Sorry, not today. Anyone else can feel free to fix it, I'm busy with cleaning up other PRs and the weekend :)

PS! It might be that you get a better google ranking for if we use the canonical URL feature instead: Check if the same file exists at $latestVersion (i.e. with the same name), and then set the latest version path as the canonical URL instead: https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls

**Comment by hasheddan** [comment]
Fixed by https://github.com/crossplane/crossplane.github.io/pull/116

**Comment by luebken** [comment]
@hasheddan I was just doing a search for "crossplane composition" and got a link to https://crossplane.io/docs/v1.1/concepts/composition.html

Looking at the HTML source I wasn't able to find `<meta name="robots" content="noindex">`

**Comment by hasheddan** [comment]
@luebken good catch! It looks like this fix went in on the wrong template. Will update 👍🏻

**Comment by negz** [comment]
A search

**Comment by negz** [comment]
A search for "Crossplane Composition" in an incognito Chrome window is still showing old docs for me. Let's keep this open until it appears to be fixed.

**Comment by jbw976** [comment]
I can at least confirm that the mechanism we are using, `<meta name="robots" content="noindex">`, is correctly recognized by Google, so that is good.

Using the Google Search Console, I can ask it to visit a specific page, e.g. an old page like https://crossplane.io/docs/v1.1/concepts/composition.html/. At first it says that it is in the index, but after requesting indexing for that page, the search console correctly shows that the URL is now no longer available to Google because of the `robots noindex` tag.

So our mechanism here is recognized by Google.

I had requested indexing of the root page https://crossplane.io/ a couple days ago, in the hopes that it would crawl the entire site including all old documentation pages, and according to https://www.reliablesoft.net/force-google-crawl-a-site/ this is the proper way to do it.  Hopefully our new noindex tags will be found by google in the near future.

I wonder if there's any ways to speed this up, the tools in google search console are pretty simple, I don't see other options or mechanisms to force crawl the entire thing immediately :(

**Comment by jbw976** [comment]
One way to perhaps watch the progress (and hope that is continues to go up) is this page that shows the set of pages that are `Excluded by ‘noindex’ tag`: https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Acrossplane.io&item_key=CAMYCCAC

Currently the value is at 113 pages 🤓

**Comment by jbw976** [comment]
I manuall requested indexing for the root documentation page of every version, e.g. https://crossplane.io/docs/v1.3/ all the way back to https://crossplane.io/docs/v0.1/.  Google now recognizes every one of those old root documentation pages as `Excluded by ‘noindex’ tag`, so hopefully this speeds us along.

**Comment by negz** [comment]
I'm still seeing results from primarily old versions when I search in an incognito Chrome window.

**Comment by jbw976** [comment]
The number of pages that Google has successfully removed from the index because of our `noindex` tag has gone up from 113 pages to 223 pages over the past week+, so progress is being made.  It's quite frustrating that you don't seem to be able to tell Google to immediately remove all `noindex` pages from the index, but at least we are seeing progress over time.

**Comment by hasheddan** [comment]
@jbw976 thanks for that update (and for working on this!). How do you feel about the strategy in https://github.com/crossplane/crossplane.github.io/pull/119? I feel like how google responds to our requests to not index old pages is a bit out of our control, so I am leaning towards just dropping versions that are no longer supported. Also, I wonder if we could _really_ annoy users trying to use old documentation by having a modal pop up (kind of how it does for joining slack, but every time a user was looking at an old docs page) and make them click something to say "yes, I know what I am doing". Anecdotally, I have almost never interacted with a user who was intentionally looking at old docs.

**Comment by jbw976** [comment]
Just reviewed and approved #119, with a small question about how future builds will handle it :)

**Comment by jbw976** [comment]
Pages that have been removed for more than a month are still showing up in google search results.  The new Google Search Console experience doesn't seem to have functionality that a lot of articles mention for removing stale/dead URLs from search.  However, I did just now find a somewhat hidden [removals tool](https://search.google.com/search-console/removals?resource_id=sc-domain%3Acrossplane.io&type=1) that allows you to request to remove URLs with a specific prefix.

I have requested the removal of docs `Starts with: https://crossplane.io/docs/v0.1` all the way to v1.1.  Please google, let this fix the issue 🙏 

![Screen Shot 2021-09-24 at 6 58 26 AM](https://user-images.githubusercontent.com/4313439/134686983-cb89ea6a-3bc6-4cad-aa60-9c5af67b0258.png)

**Comment by negz** [comment]
I just did a bit of Googling for some terms like "crossplane composition", "crossplane packages", and "crossplane aws" and did not get any ancient docs links. :o Perhaps this has finally been resolved? I did note a few slightly older blog posts etc, but nothing earlier than v1.1.

**Comment by negz** [comment]
Aha - I notice that we just don't have older docs versions anymore so that's probably why haha. I think we can close this.

**Comment by jbw976** [comment]
Thanks for confirming @negz!

> Aha - I notice that we just don't have older docs versions anymore so that's probably why haha. I think we can close this.

Actually google still didn't remove the search results for old pages that didn't exist anymore - this was not solved until explicitly requesting removals in the google search console. Annoying that an explicit action had to be taken on our part, but glad we've gotten the result that we wanted now.
